["    @Test\n    public void test1() throws Throwable {\n        if (debug)\n            System.out.format(\"%n%s%n\", \"RegressionTest0.test1\");\n        java.lang.Throwable throwable0 = null;\n        // The following exception was thrown during execution in test generation\n        try {\n            com.alibaba.nacos.api.remote.response.Response response1 = com.alibaba.nacos.api.remote.response.ErrorResponse.build(throwable0);\n            org.junit.Assert.fail(\"Expected exception of type java.lang.NullPointerException; message: null\");\n        } catch (java.lang.NullPointerException e) {\n            // Expected exception.\n        }\n    }\n"]